---
title: "OTFE"
date: "November 2024"
output:
  html_document:
    df_print: paged
---

This document may be used to analyze the data. For now, it just loads the data. 

# Getting started: Importing the raw data, loading libraries, and checking all variables are populated.

```{r}
# Set the working directory

library(tidyverse)
library(purrr)
library(jsonlite)
library(extrafont)
library(factoextra)
library(GGally)

csv_file <- "data/all_apps_wide-2024-11-13.csv"
df <- read_csv(csv_file) 
df <- df %>% filter(participant.finished == 1)

# Define the folder name variable
folder_name <- "output_2024-11-13"

output_folder <- paste0("output/", folder_name)
# Create the new folder in the working directory if it doesn't exist
if (!dir.exists(output_folder)) {
  dir.create(output_folder)
}
```

```{r}
# Plot duration
df <- df %>%
  mutate(
    # Convert Duration..in.seconds. from string to numeric (seconds)
    duration_seconds = participant.end_time - participant.start_time,
    # Create duration_minutes by dividing duration_seconds by 60
    duration_minutes = duration_seconds / 60
  ) 

# Print the average duration
# Calculate the average of variable Y
average_duration <- df %>%
  summarise(average = mean(duration_minutes, na.rm = TRUE)) %>%  # Calculate the mean, ignoring NA values
  pull(average)  # Extract the mean value

# Print the average of Y
print(average_duration)

# Create the plot for duration_minutes and save it
plot <- df %>%
  ggplot(aes(x = duration_minutes)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black") +
  labs(title = "Distribution of Duration in Minutes",
       x = "Duration (minutes)",
       y = "Frequency") +
  theme_minimal()

print(plot)
# Save the plot to the specified folder
ggsave(filename = file.path(output_folder, "duration_minutes_distribution.png"),
       plot = plot,
       width = 8, height = 6)
```


```{r}

# Print the average payment
# Calculate the average of variable Y
average_payoff <- df %>%
  summarise(average = mean(participant.payoff, na.rm = TRUE)) %>%  # Calculate the mean, ignoring NA values
  pull(average)  # Extract the mean value

# Print the average of Y
print(average_payoff)

# Create the plot for duration_minutes and save it
plot <- df %>%
  ggplot(aes(x = participant.payoff)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black") +
  labs(title = "Distribution of Payoff",
       x = "Payoff ($)",
       y = "Frequency") +
  theme_minimal()

print(plot)
# Save the plot to the specified folder
ggsave(filename = file.path(output_folder, "payoff_distribution.png"),
       plot = plot,
       width = 8, height = 6)
```
```{r}
# Define the levels in the order you want them to appear
df$participant.treatment <- factor(df$participant.treatment, 
                                   levels = c('C-Info', 'C-NoInfo', 'T1-T-Info', 'T1-T-NoInfo', 'T1-P', 'T2-T'))

# Create the bar chart
plot <- ggplot(df, aes(x = participant.treatment)) +
  geom_bar(fill = "skyblue", color = "black") +
  labs(x = "Participant Treatment", y = "Frequency", title = "Frequency of Each Treatment Group") +
  theme_minimal()


print(plot)
# Save the plot to the specified folder
ggsave(filename = file.path(output_folder, "treatment_distribution.png"),
       plot = plot,
       width = 8, height = 6)

```


```{r}

# Parse the JSON in each row and create new columns for correctAttempts and incorrectAttempts
json_columns <- c("participant.attempts_training", "participant.attempts_work_1", 
                  "participant.attempts_work_2", "participant.attempts_work_3")
prefixes <- c("training", "work_1", "work_2", "work_3")

# Loop over the columns and prefixes
for (i in seq_along(json_columns)) {
  column <- json_columns[i]
  prefix <- prefixes[i]
  
  # Parse JSON and create new columns for correctAttempts and incorrectAttempts with the specified prefix
  df <- df %>%
    mutate(parsed_json = map(!!sym(column), ~ fromJSON(.))) %>%
    mutate(
      !!paste0(prefix, "_correctAttempts") := map_int(parsed_json, "correctAttempts"),
      !!paste0(prefix, "_incorrectAttempts") := map_int(parsed_json, "incorrectAttempts")
    ) 
}
```

```{r}
df <- df %>%
  rename(
    cq_1_mistakes = participant.cq_1_mistakes,
    cq_2_mistakes = participant.cq_2_mistakes
  )

```

```{r}
belief_columns <- c("beliefs1", "beliefs1", "beliefs1_2", "beliefs1_3", "beliefs2", "beliefs2_2", "beliefs2_3", "beliefs3", "beliefs4")

# Remove the 'participant.' prefix only from specified columns
df <- df %>%
  rename_with(~ gsub("^participant\\.", "", .), 
              .cols = starts_with("participant.") & ends_with(belief_columns))

survey_columns <- c('survey_student_loans', 'survey_pandemic', 'survey_wealth_tax_consumption', 
                    'survey_wealth_tax_savings', 'survey_wealth_tax_personal_savings', 
                    'survey_wealth_tax_personal_consumption', 'survey_repatriation', 
                    'survey_one_time_policies', 'survey_tax_rates_1', 'survey_tax_rates_2', 
                    'survey_tax_rates_3', 'survey_tax_rates_4', 'survey_tax_rates_5')

# Use grep to find columns that start with 'otfe.1.player.' and end with any of the survey_columns
df <- df %>%
  rename_with(~ gsub("^otfe\\.1\\.player\\.", "", .), 
              .cols = starts_with("otfe.1.player.") & ends_with(survey_columns))

```

```{r}
feedback_columns <- c("feedback", "feedback_difficulty", "feedback_understanding", "feedback_satisfied", "feedback_pay")

# Remove the 'participant.' prefix only from specified columns
df <- df %>%
  rename_with(~ gsub("^participant\\.", "", .), 
              .cols = starts_with("participant.") & ends_with(feedback_columns))

```
